import { RiskItem } from './types';

// Data extracted specifically from the RAS PDF for Via Betulle 24
export const rasData: RiskItem[] = [
  {
    id: '1',
    title: 'Polizza Assicurativa Scaduta',
    description: 'La polizza globale fabbricati risulta scaduta il 28/02/2010. Il condominio è privo di copertura.',
    priority: '1',
    status: 'Non Iniziato',
    area: 'Assicurazione',
    cost: 2500,
    costRange: '€€',
    deadline: '2025-05-20', // Immediate
    owner: 'Amministratore',
    impact: 'Copertura rischi civili e patrimoniali',
    legalRisk: 'Patrimoniale',
    urgency: 'Immediato'
  },
  {
    id: '2',
    title: 'Messa in Sicurezza Facciate',
    description: 'Ammaloramenti visibili su frontalini e sottobalconi. Rischio caduta calcinacci.',
    priority: '2',
    status: 'Non Iniziato',
    area: 'Strutturale',
    cost: 45000,
    costRange: '€€€',
    deadline: '2025-06-15',
    owner: 'Impresa Edile',
    impact: 'Eliminazione rischio danni a terzi',
    legalRisk: 'Penale',
    urgency: 'Immediato'
  },
  {
    id: '3',
    title: 'Accesso Copertura/Torrino',
    description: 'Scala attuale non sicura. Necessaria installazione scala a norma e parapetti verso il vuoto.',
    priority: '2',
    status: 'Non Iniziato',
    area: 'Strutturale',
    cost: 3500,
    costRange: '€€',
    deadline: '2025-07-01',
    owner: 'Fabbro/Tecnico',
    impact: 'Sicurezza manutentori (D.Lgs 81/08)',
    legalRisk: 'Penale',
    urgency: 'Breve Termine'
  },
  {
    id: '4',
    title: 'Certificazione Prevenzione Incendi (CPI/SCIA)',
    description: 'Attività 74 (Centrale Termica) e 75 (Autorimessa) prive di SCIA Antincendio e documentazione.',
    priority: '2',
    status: 'Non Iniziato',
    area: 'Normativa',
    cost: 8000,
    costRange: '€€',
    deadline: '2025-08-01',
    owner: 'Tecnico Abilitato',
    impact: 'Conformità antincendio DPR 151/2011',
    legalRisk: 'Penale',
    urgency: 'Breve Termine'
  },
  {
    id: '5',
    title: 'Installazione Linee Vita',
    description: 'Installazione sistemi anticaduta UNI EN 795 per manutenzione tetto.',
    priority: '2',
    status: 'Non Iniziato',
    area: 'Strutturale',
    cost: 5000,
    costRange: '€€',
    deadline: '2025-09-01',
    dependencies: ['3'],
    owner: 'Ditta Specializzata',
    impact: 'Accessibilità sicura copertura',
    legalRisk: 'Civile',
    urgency: 'Medio Termine'
  },
  {
    id: '6',
    title: 'Abbattimento Barriere Architettoniche',
    description: 'Installazione servo-scala per accessibilità disabili (fabbricato privo di ascensore).',
    priority: '1',
    status: 'In Corso',
    area: 'Strutturale',
    cost: 12000,
    costRange: '€€€',
    deadline: '2025-10-01',
    owner: 'Fornitore Ascensori',
    impact: 'Accessibilità e valore immobile',
    legalRisk: 'Civile',
    urgency: 'Medio Termine'
  },
  {
    id: '7',
    title: 'Illuminazione Emergenza',
    description: 'Assente nei passaggi comuni e vano scale. Installazione lampade.',
    priority: '3',
    status: 'Non Iniziato',
    area: 'Impianti',
    cost: 2000,
    costRange: '€',
    deadline: '2025-06-30',
    owner: 'Elettricista',
    impact: 'Sicurezza esodo',
    legalRisk: 'Civile',
    urgency: 'Breve Termine'
  },
  {
    id: '8',
    title: 'Adeguamento GDPR Privacy',
    description: 'Nomina responsabile trattamento, registro attività, informative condomini e videosorveglianza.',
    priority: '3',
    status: 'Non Iniziato',
    area: 'Normativa',
    cost: 800,
    costRange: '€',
    deadline: '2025-06-01',
    owner: 'Amministratore',
    impact: 'Compliance Regolamento UE 679/2016',
    legalRisk: 'Amministrativo',
    urgency: 'Breve Termine'
  },
  {
    id: '9',
    title: 'Verifica Impianto Messa a Terra',
    description: 'Verifica periodica DPR 462/01. Ultima verifica luglio 2024 (OK), programmare prossima.',
    priority: '3',
    status: 'Completato',
    area: 'Impianti',
    cost: 0,
    costRange: '€',
    deadline: '2026-07-01',
    owner: 'Ente Certificatore',
    impact: 'Sicurezza elettrica',
    legalRisk: 'Penale',
    urgency: 'Lungo Termine'
  },
  {
    id: '10',
    title: 'Registro Anagrafe Sicurezza Fornitori',
    description: 'Raccolta DUVRI e verifica idoneità tecnico-professionale imprese (art. 26 D.Lgs 81/08).',
    priority: '3',
    status: 'In Corso',
    area: 'Documentale',
    cost: 0,
    costRange: '€',
    deadline: '2025-05-30',
    owner: 'Amministratore',
    impact: 'Tutela committente',
    legalRisk: 'Penale',
    urgency: 'Immediato'
  },
  {
    id: '11',
    title: 'Manutenzione Estintori/Idranti',
    description: 'Attivare contratto manutenzione semestrale e registro controlli (UNI 9994-1).',
    priority: '2',
    status: 'Non Iniziato',
    area: 'Impianti',
    cost: 600,
    costRange: '€',
    deadline: '2025-05-25',
    owner: 'Ditta Antincendio',
    impact: 'Efficienza presidi antincendio',
    legalRisk: 'Penale',
    urgency: 'Immediato'
  },
  {
    id: '12',
    title: 'Adeguamento Cancello Carrabile',
    description: 'Marcatura CE, manuale manutenzione, verifica fotocellule/coste per cancello post-2005.',
    priority: '3',
    status: 'Non Iniziato',
    area: 'Impianti',
    cost: 1500,
    costRange: '€',
    deadline: '2025-09-15',
    owner: 'Fabbro/Elettricista',
    impact: 'Sicurezza meccanica (Direttiva Macchine)',
    legalRisk: 'Civile',
    urgency: 'Medio Termine'
  },
  {
    id: '13',
    title: 'Valutazione Rischio Fulminazione',
    description: 'Redazione documento valutazione rischio CEI EN 62305.',
    priority: '3',
    status: 'Non Iniziato',
    area: 'Normativa',
    cost: 800,
    costRange: '€',
    deadline: '2025-07-15',
    owner: 'Ingegnere',
    impact: 'Prevenzione danni atmosferici',
    legalRisk: 'Civile',
    urgency: 'Medio Termine'
  },
  {
    id: '14',
    title: 'Pavimentazione Scale',
    description: 'Ripristino gradini sbeccati e installazione strisce antiscivolo.',
    priority: '3',
    status: 'Non Iniziato',
    area: 'Strutturale',
    cost: 2500,
    costRange: '€',
    deadline: '2025-11-01',
    owner: 'Impresa Edile',
    impact: 'Prevenzione cadute',
    legalRisk: 'Civile',
    urgency: 'Medio Termine'
  },
  {
    id: '15',
    title: 'Fascicolo Emergenza (DM 25/01/2019)',
    description: 'Redazione piano di emergenza ed evacuazione con planimetrie.',
    priority: '2',
    status: 'Non Iniziato',
    area: 'Documentale',
    cost: 1200,
    costRange: '€',
    deadline: '2025-06-01',
    owner: 'Tecnico Antincendio',
    impact: 'Gestione emergenze',
    legalRisk: 'Penale',
    urgency: 'Breve Termine'
  }
];